version: "3"
services:
  eye_nginx:
    image: lihn1011/nginx:0.6
    container_name: eye_nginx
    command: /bin/bash -c "while true;nginx -g 'daemon off;';do sleep 1 ; done"
    volumes:
      - ./data/nginx/config/default:/etc/nginx/sites-enabled/default
      - ./data/nginx/src/:/var/www/html/
    ports:
      - "9980:80"

  eye_rest:
    container_name: eye_rest
    image: lihn1011/rest:0.5
    command: /bin/bash -c "cd /opt/; while true;do sleep 3;python3 -u manage.py runserver 0.0.0.0:80; sleep 1 ; done"
    volumes:
        - ../backend/rest/main/:/opt/
    restart: always
    expose:
        - 80
    ports:
        - "9979:80"
        
  eye_block:
    container_name: eye_block
    image: lihn1011/ubuntu:0.7
    command: /bin/bash -c "cd /opt/tools/; while true; do python3 -u create_testnet.py create; sleep 1 ; done"
    volumes:
        - ../substrate/:/opt/
    restart: always
    expose:
        - 9001
    ports:
        - "9001:9001"
        - "9004:9004"
        - "9007:9007"
        - "9010:9010"

  eye_chain_api:
    container_name: eye_chain_api
    image: lihn1011/polka_nodejs:0.2
    command: /bin/bash -c "cd /opt/; while true;do sleep 3; sleep 1 ; done"
    volumes:
        - ../eye_api/:/opt/
    restart: always
    expose:
        - 3000
    ports:
        - "9901:3000"

